version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: apatight
      POSTGRES_USER: pooja
      POSTGRES_PASSWORD: shturve
    restart: always
    ports:
        - "5432:5432"